config/routes.rb
Rails.application.routes.draw do
  get 'bundle_lines/create'
  devise_for :users
  root to: 'pages#home'
  get 'pages/design', to: 'pages#design'
  get 'pages/home-page-v2', to: 'pages#home_2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bundles, only: [:new, :create, :show] do
    resources :bundle_lines, only: [:create, :edit, :update]
    resources :payments, only: [:create]
    member do
      get 'location'
      get 'services'
    end
  end

  resources :bundle_lines, only: :destroy


  resources :suppliers, only: [:index, :new, :create] do
    resources :services, only: [:index]
    resources :availabilities, only: [:new, :create]
    resources :images, only: [:new, :create]
  end

end

app/models/area.rb
class Area < ApplicationRecord
  has_many :suppliers
  before_validation :validation_area

  def working_area
    "#{department}, #{region}, #{country}"
  end

  private

  def validation_area
    if country.nil? && region.nil? && department.nil? && city.nil?
      errors.add(:country, "Specify at least a country")
    end
  end
end

app/models/bundle.rb
class Bundle < ApplicationRecord
  belongs_to :user
  has_many :bundle_lines
  has_many :suppliers, through: :bundle_lines
  monetize :amount_cents
  validates :state, inclusion: { in: ['pending', 'cancelled', 'paid', 'confirmed', 'refunded', 'completed'] }

  attr_accessor :supplier_ids
  # confirmed = payment accpeted + boooking confirmed
  # cancelled = after payment if user wants to retract
  # completed = after wedding when user wants to add a review
end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  def show
    @bundle = Bundle.find(params[:id])
  end

  def new
    @bundle = Bundle.new
  end

  def create
    session[:bundle] = {}
    session[:bundle][:starts_on] = params[:starts_on]
    session[:bundle][:ends_on] = params[:ends_on]
    session[:bundle][:where] = params[:where]
    session[:bundle][:capacity] = params[:capacity]
    session[:bundle][:budget] = params[:budget]
    session[:bundle][:categories] = params[:categories]
    @bundle = Bundle.new
    @bundle.user = current_user
    @bundle.starts_on = params[:starts_on]
    @bundle.ends_on = params[:ends_on]
    @bundle.capacity = params[:capacity]
    @bundle.save
    if params[:categories].nil? || params[:starts_on].nil? || params[:ends_on].nil? || params[:where].nil? || params[:capacity].nil? || params[:budget].nil?
      render :new
    elsif params[:categories].include?("lieu")
      redirect_to location_bundle_path(@bundle)
    else
      redirect_to services_bundle_path(@bundle)
    end
  end

  def location
    @bundle = Bundle.find(params[:id])
    @places_suppliers = Supplier.near(session[:bundle]['where'], 80).where.not(latitude: nil, longitude: nil)
    # start_date = DateTime.parse(session[:bundle]['starts_on'])
    # end_date = DateTime.parse(session[:bundle]['ends_on'])
    # dates = session[:bundle]['starts_on'].split(' au ')
    # start_date = DateTime.parse(dates.first)
    # end_date = DateTime.parse(dates.last)
    @event_days = (@bundle.starts_on..@bundle.ends_on).map{ |a| a }

    @places_suppliers = check_availabilities(@places_suppliers)
    @places_suppliers = check_budget(@places_suppliers)
    @places_suppliers = check_capacity(@places_suppliers)

    @markers = @places_suppliers.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        supplier_id: place.id,
        place_price: ActionController::Base.helpers.humanized_money(place.price * @event_days.count, symbol_first: false, no_cents: true),
        infoWindow: { content: render_to_string(partial: "/bundles/map_box", locals: { place: place }) }
      }
    end
    @places_suppliers
  end

  def services
    # 1 - Selection of all suppliers that are not 'lieu'
    @services_supplier = Supplier.joins(:service).where.not(services: { category: 'lieu' })
    # 2 - bundle that we are building
    @bundle = Bundle.find(params[:id])
    # 3 - selected services on the new bundle page
    @services_selected = session[:bundle]["categories"]
    # 4 - check session where en fct des areas des suppliers (autres services)
    # a) get region from address put in the form by the user
    geocode_where = Geocoder.search(session[:bundle]['where'])
    array_geocode = geocode_where.first.address_components
    region = ""
    array_geocode.each do |address_component|
      if address_component["types"].first == "administrative_area_level_1"
        region = address_component["long_name"]
      end
    end
    # b) keep only suppliers which area is variable region
    @services_supplier = @services_supplier.select do |service_supplier|
      service_supplier.area.region == region
    end
    # 5 - check availabilities by comparing dates of user and availabilities of suppliers
    # a) get  start and end dates entered by user and transform it in an array of dates
    start_date = DateTime.parse(session[:bundle]['starts_on'])
    end_date = DateTime.parse(session[:bundle]['ends_on'])
    @event_days = (start_date..end_date).map{ |a| a }
    # b) call check_availabilities method to filter suppliers
    @services_supplier = check_availabilities(@services_supplier)
    # what's above is ok
    #--------------------------------------------------------------------------

    # 6 - check budget
    # a) check if lieu was selected to build a remaining budget
    # b) differenciate budget traiteur with other services
    total_budget = Money.new(session[:bundle]['budget'].to_i * 100, "eur")
    capacity = session[:bundle]['capacity'].to_i
    @services_supplier = @services_supplier.select do |service_supplier|
      if @services_selected.include?("lieu")
        # get price of the chosen lieu
        location_budget = Money.new(@bundle.suppliers.first.price.to_i * @event_days.count * 100, "eur")
        remaining_budget = total_budget - location_budget
        nb_of_other_services = @services_selected.count - 1
        if @services_selected.include?("traiteur")
          nb_of_other_services = @services_selected.count - 2
          caterer_budget = 0.7 * remaining_budget
          if service_supplier.service.category == "traiteur"
            service_supplier.price * capacity <= caterer_budget
          else
            remaining_budget = remaining_budget - caterer_budget
            other_services_budget = remaining_budget / nb_of_other_services
            service_supplier.price <= other_services_budget
          end
        else
          other_services_budget = remaining_budget / nb_of_other_services
          service_supplier.price <= other_services_budget
        end
      else
        remaining_budget = Money.new(session[:bundle]['budget'].to_i * 100, "eur")
        if @services_selected.include?("traiteur")
          nb_of_other_services = @services_selected.count - 1
          caterer_budget = 0.7 * remaining_budget
          if service_supplier.service.category == "traiteur"
            service_supplier.price * capacity <= caterer_budget
          else
            remaining_budget = remaining_budget - caterer_budget
            other_services_budget = remaining_budget / nb_of_other_services
            service_supplier.price <= other_services_budget
          end
        else
          other_services_budget = remaining_budget / nb_of_other_services
          service_supplier.price <= other_services_budget
        end
      end
    end
    @services_selected.delete("lieu")
    @services_supplier
  end

  def check_availabilities(suppliers)
    return suppliers.select do |supplier|
      supplier.availabilities.map do |avail|
        (avail.starts_on..avail.ends_on).map{ |a| a }.flatten.uniq.include?(@event_days)
      end
    end
  end

  def check_budget(suppliers)
    nb_days = @event_days.count
    budget = session[:bundle]['budget'].to_i
    return suppliers.select do |supplier|
      (supplier.price.to_f * nb_days) <= (0.3 * budget)
    end
  end

  def check_capacity(suppliers)
    return suppliers.select do |supplier|
      supplier.capacity >= @bundle.capacity
    end
  end
end

app/views/bundles/_confirmation.html.erb
<div class="confirmation">
  <div class="confirmation-photo">
  </div>
  <div class="confirmation-message">
    <h4><strong>Félicitations <%= current_user.first_name %> !</strong></h4><br>
    <p>
      Votre paiement a bien été effectué. A présent, l'équipe Wedpacker s'occupe de tout !
      <br><br>
      Un email contenant un <strong>récapitulatif</strong> de votre commande, ainsi que les <strong>informations</strong> relatives à toutes vos prestations vous a été envoyé.
      <br><br> N'hésitez pas à nous contacter à l'adresse <strong>customer.service@wedpacker.com</strong> pour plus de renseignements.
      <br><br> Nous vous remercions pour votre confiance !
      <br><br>
      <div id="#team-logo"><%= image_tag "logo_wp_blue.png", height: 25 %> <em><strong>Team</strong></em></div>
    </p>
  </div>
</div>

app/views/bundles/_map_box.html.erb
<div id="map-box">
  <%= place.service_name %>
</div>

app/views/bundles/_pending_payment.html.erb
<%= form_tag bundle_payments_path(bundle), id: "payment-form" do %>
  <%= hidden_field_tag :stripeToken, nil, id: "stripe-token" %>

  <button id="payment-button"
    class="btn-validate"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-logo="<%= image_url 'logo_payment.png' %>"
    data-locale="fr"
    data-name="Mon package de mariage"
    data-description="Pour <%= bundle.suppliers.count %> prestation(s)"
    data-email="<%= current_user.email %>"
    data-amount="<%= bundle.amount_cents %>"
    data-currency="<%= bundle.amount.currency %>">
    Payer en ligne
  </button>
<% end %>

app/views/bundles/create.html.erb
<h1>Bundles#create</h1>
<p>Find me in app/views/bundles/create.html.erb</p>

app/views/bundles/location.html.erb
<div class="container">
  <% if @places_suppliers == [] %>
    <div>
      <h3>Nous sommes désolés.<br>Aucun résultat ne correspond à votre recherche</h3>
      <%= link_to "Relancer une recherche", new_bundle_path, class: "btn-validate" %>
    </div>
  <% else %>
    <div class="thread">
      <div class="b-box b-box--dots">
        <span class="b-box--dots__item is-active"></span>
        <span class="b-box--dots__item is-active"></span>
        <span class="b-box--dots__item"></span>
        <span class="b-box--dots__item"></span>
        <span class="b-box--dots__item big">
          <span data-amount=<%= @bundle.amount.to_i %> id="amount">
            <%= humanized_money(@bundle.amount) %>
          </span>
          €
        </span>
      </div>
      <div class="list-items">
        <div class="item"><%= link_to "Recherche", new_bundle_path %></div>
        <div class="item"><%= link_to "Lieu", location_bundle_path(@bundle) %></div>
        <div class="item"></div>
        <div class="item"></div>
      </div>
    </div>

    <div class="results-container">
      <!-- Column with Map -->
      <div class="map-container">
        <div id="map" data-markers="<%= @markers.to_json %>"></div>
      </div>
      <!-- Column with Card -->
      <div class="places-content">
        <!--<%# @places_suppliers.each do |supplier| %>
                <%#= cl_image_tag supplier.images.first.photo, width: 700, crop: :fit, class: "places-images supplier-photo #{"hidden" unless @places_suppliers.first == supplier}", id: "supplier-photo-#{supplier.id}" %>
            <%# end %> -->

        <!-- Carousel -->
        <div class = places-details>
          <% @places_suppliers.each do |supplier| %>
            <div id="supplier-photo-<%= supplier.id %>" class="supplier-photo <%= "hidden" unless @places_suppliers.first == supplier %> ">
              <div id="carousel-supplier-<%= supplier.id %>" class="carousel slide" data-ride="carousel" data-interval="false">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <% supplier.images.each_with_index do |_image, index| %>
                      <li data-target="#carousel-supplier-<%= supplier.id %>" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
                    <% end %>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <% supplier.images.each_with_index do |image, index| %>
                      <div class="places-images item<%= ' active' if index == 0 %>" style='background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= cl_image_path image.photo %>);'>
                        <%#= cl_image_tag image.photo, width: 500, crop: :fit, class: "places-images" %>
                      </div>
                    <% end %>
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-supplier-<%= supplier.id %>" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-supplier-<%= supplier.id %>" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
            <!-- Carousel end -->
            <div class="card-supplier-footer supplier-details <%= "hidden" unless @places_suppliers.first == supplier %>" id="supplier-details-<%= supplier.id %>">
              <h3><%= supplier.service_name %></h3>
              <p class="card-rating">
                <% if supplier.avg_rating >= 4.5 && supplier.avg_rating <= 4.75 %>
                  <% supplier.avg_rating.to_i.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <i class="fas fa-star-half"></i>
                <% else %>
                  <% supplier.avg_rating.ceil.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                <% end %>
              </p>
              <p class="card-price" ><%= humanized_money(supplier.price * @event_days.count) %>€</p>
              <%= link_to "#", class: "card-details card-details-flex", id: "button-details" do %>
                <p>Détails </p><i class="fas fa-angle-up"></i>
              <% end %>
            </div>
            <div class="place-description supplier-description <%= "hidden" unless @places_suppliers.first == supplier %>" id="supplier-description-<%= supplier.id %>">
              <div class="place-description-content">
                <p><i class="fas fa-quote-left"></i> <%= supplier.description %> <i class="fas fa-quote-right"></i></p>
                <i class="fas fa-angle-down"></i>
              </div>
            </div>
          <% end %>
        </div>
        <div>
          <%= form_tag bundle_bundle_lines_path(@bundle), method: :post, class: "form-inline text-right" do %>
            <%= hidden_field_tag :supplier_id, @places_suppliers.first.id %>
            <%= button_tag class:'btn-validate', id: 'lock', type: "submit" do %>
              <span>Réserver</span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/bundles/new.html.erb
<div class="container">
  <div class="thread">
    <div class="b-box b-box--dots">
      <span class="b-box--dots__item is-active"></span>
      <span class="b-box--dots__item"></span>
      <span class="b-box--dots__item"></span>
      <span class="b-box--dots__item"></span>
      <span class="b-box--dots__item big"> 0 € </i></span>
    </div>
    <div class="list-items">
      <div class="item"><%= link_to "Recherche", new_bundle_path %></div>
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
    </div>
  </div>
  <div class="row form-row">
    <div class="col-xs-6">
      <h4>Remplissez le formulaire et cliquez <br>sur les prestations souhaitées</h4>
      <div class="form-search">
        <%= form_tag bundles_path do %>
          <div class="date-form">
            <%= text_field_tag :starts_on, params[:starts_on], class: "form-control styled-form datepicker start_date small-form", placeholder: "Du..." %>
            <%= text_field_tag :ends_on, params[:ends_on], class: "form-control styled-form datepicker end_date small-form", placeholder: "Au..." %>
          </div>
          <div class="location-form">
            <%= text_field_tag :where, params[:where], class: "form-control styled-form", placeholder: "Oú ?" %>
          </div>
          <div class="capacity-budget-form">
            <%= text_field_tag :capacity, params[:capacity], class: "form-control styled-form small-form", placeholder: "Nombre d'invités" %>
            <%= text_field_tag :budget, params[:budget], class: "form-control styled-form small-form", placeholder: "Budget" %>
          </div>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="service-cards">
        <div class="row ">
          <%= check_box_tag "categories[]", :lieu, checked=false, id: :categories_place, class: "categories" %>
            <div class="col-xs-4">
              <label for="categories_place" class="categories_place" id='location' >
                <div class="service-card not-selected label-handle" >
                  <div>
                    <%= image_tag 'lieu.png', class:'small-picture' %>
                    <h4>Lieu</h4>
                  </div>
                </div>
                <div class="service-card chosen-service selected hidden categories_place label-handle" id="location">
                  <div>
                    <i class="far fa-check-circle"></i>
                    <h4>Lieu ajouté à votre recherche</h4>
                  </div>
                </div>
              </label>
            </div>
          <%= check_box_tag "categories[]", :traiteur, checked=false, id: :categories_catering, class: "categories" %>
            <div class="col-xs-4">
              <label for="categories_catering">
                <div class="service-card not-selected label-handle" id="food">
                  <div>
                    <%= image_tag 'traiteur.png', class:'small-picture' %>
                    <h4>Traiteur</h4>
                  </div>
                </div>
                <div class="service-card chosen-service selected hidden label-handle" id="food">
                  <div>
                    <i class="far fa-check-circle"></i>
                    <h4>Traiteur ajouté à votre recherche</h4>
                  </div>
                </div>
              </label>
            </div>
          <%= check_box_tag "categories[]", :musique, checked=false, id: :categories_music, class: "categories" %>
            <div class="col-xs-4">
              <label for="categories_music">
                <div class="service-card not-selected label-handle" id="music">
                  <div>
                    <%= image_tag 'musique.png', class:'small-picture' %>
                    <h4>Musique</h4>
                  </div>
                </div>
                <div class="chosen-service selected hidden label-handle" id="music">
                  <div>
                    <i class="far fa-check-circle"></i>
                    <h4>Musique ajouté à votre recherche</h4>
                  </div>
                </div>
              </label>
            </div>
          <%= check_box_tag "categories[]", :fleuriste, checked=false, id: :categories_flower, class: "categories" %>
            <div class="col-xs-4">
              <label for="categories_flower">
                <div class="service-card not-selected label-handle" id="flower">
                  <div>
                    <%= image_tag 'fleuriste.png', class:'small-picture' %>
                    <h4>Fleuriste</h4>
                  </div>
                </div>
                <div class="chosen-service selected hidden label-handle" id="flower">
                  <div>
                    <i class="far fa-check-circle"></i>
                    <h4>Fleuriste ajouté à votre recherche</h4>
                  </div>
                </div>
              </label>
            </div>
          <%= check_box_tag "categories[]", :photographe, checked=false, id: :categories_photograph, class: "categories" %>
            <div class="col-xs-4">
              <label for="categories_photograph">
                <div class="service-card not-selected label-handle" id="photo">
                  <div>
                    <%= image_tag 'photographe.png', class:'small-picture' %>
                    <h4>Photographe</h4>
                  </div>
                </div>
                <div class="chosen-service selected hidden label-handle" id="photo">
                  <div>
                    <i class="far fa-check-circle"></i>
                    <h4>Photographe ajouté à votre recherche</h4>
                  </div>
                </div>
              </label>
            </div>
          <%= check_box_tag "categories[]", :animations, checked=false, id: :categories_entertainment, class: "categories" %>
            <div class="col-xs-4">
              <label for="categories_entertainment">
                <div class="service-card not-selected label-handle" id="animation">
                  <div>
                  <%= image_tag 'animations.png', class:'small-picture' %>
                  <h4>Animations</h4>
                  </div>
                </div>
                <div class="chosen-service selected hidden label-handle" id="animation">
                  <div>
                    <i class="far fa-check-circle"></i>
                    <h4>Animations ajoutées à votre recherche</h4>
                  </div>
                </div>
              </label>
            </div>
            <div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= button_tag class:'btn-validate btn-search', type: "submit" do %>
      <span>Rechercher</span>
    <% end %>
  <% end %>
</div>

app/views/bundles/show.html.erb
<% if @bundle.state == "pending" %>
  <div class="container">
    <div class="thread">
      <div class="b-box b-box--dots">
        <span class="b-box--dots__item is-active"></span>
        <span class="b-box--dots__item is-active"></span>
        <span class="b-box--dots__item is-active"></span>
        <span class="b-box--dots__item is-active"></span>
        <span class="b-box--dots__item big">
          <span data-amount=<%= @bundle.amount.to_i %> id="amount">
            <%= humanized_money(@bundle.amount) %>
          </span>
          €
        </span>
      </div>


      <div class="list-items">
        <div class="item-last"><%= link_to "Recherche", new_bundle_path %></div>
        <div class="item-last"><%= link_to "Lieu", location_bundle_path(@bundle) %></div>
        <div class="item-last"><%= link_to "Services", services_bundle_path(@bundle) %></div>
        <div class="item-last"><%= link_to "Récapitulatif", bundle_path(@bundle) %></div>
      </div>
    </div>
    <div class="row" style="margin-top: 40px">
      <% @bundle.bundle_lines.each do |bundle_line| %>
        <div class="col-xs-8 col-xs-offset-2 bundle-recap" data-id="<%= bundle_line.id %>">
          <div class="list-element">
            <% if bundle_line.supplier.service.category == "lieu" %>
              <div class="list-image"><%= image_tag 'lieu.png', class:'extra-small-picture' %></div>
            <% elsif bundle_line.supplier.service.category == "animations"%>
              <div class="list-image"><%= image_tag 'animations.png', class:'extra-small-picture' %></div>
            <% elsif bundle_line.supplier.service.category == "traiteur"%>
            <div class="list-image"><%= image_tag 'traiteur.png', class:'extra-small-picture' %></div>
            <% elsif bundle_line.supplier.service.category == "musique"%>
             <div class="list-image"><%= image_tag 'musique.png', class:'extra-small-picture' %></div>
            <% elsif bundle_line.supplier.service.category == "photographe"%>
            <div class="list-image"><%= image_tag 'photographe.png', class:'extra-small-picture' %></div>
            <% elsif bundle_line.supplier.service.category == "fleuriste"%>
            <div class="list-image"><%= image_tag 'fleuriste.png', class:'extra-small-picture' %></div>
            <% end %>


            <div class="list-title"><h5><%= bundle_line.supplier.service_name  %></h5></div>
            <div class="price">
              <div><h5><%= humanized_money(bundle_line.amount) %>€</h5></div>
            </div>
              <%= link_to bundle_line_path(bundle_line), method: :delete, data: { confirm: "Etes vous sûr de vouloir supprimer cette prestation ?" } do %>
                <i class="fas fa-times-circle trash"></i>
              <% end %>
            <div class="angle">
              <a class="" data-toggle="collapse" href="#bundle-line-details-<%= bundle_line.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
                <i class="fas fa-angle-right"></i>
              </a>
            </div>
          </div>
          <div class="collapse" id="bundle-line-details-<%= bundle_line.id %>">
            <div class= "card card-body">
              <div class="card-image">
               <%= cl_image_tag bundle_line.supplier.images.first.photo, crop: :fill, height: 400, width: 400 %>
              </div>
              <div class="description">
                <h6><strong><%= bundle_line.supplier.service_name %></strong></h6>
                <p> <%= bundle_line.supplier.description %></p>
                <p>
                  <strong>Le petit <i class="fas fa-plus plus"></i></strong> : <%= bundle_line.supplier.originality%>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= content_for :before_js do %>
      <script src="https://checkout.stripe.com/checkout.js"></script>
    <% end %>

    <div class="payment-info">
      <h3>Prix Total:</h3>
      <h4><strong><%= humanized_money(@bundle.amount) %>€</strong></h4>
      <%= render "pending_payment", bundle: @bundle %>
    </div>

  </div>
<% else %>
    <!-- display confirmation message -->
    <%= render "confirmation" %>
<% end %>