config/routes.rb
Rails.application.routes.draw do
  get 'bundle_lines/create'
  devise_for :users
  root to: 'pages#home'
  get 'pages/design', to: 'pages#design'
  get 'pages/home-page-v2', to: 'pages#home_2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bundles, only: [:new, :create, :show] do
    resources :bundle_lines, only: [:create, :edit, :update]
    resources :payments, only: [:create]
    member do
      get 'location'
      get 'services'
    end
  end

  resources :bundle_lines, only: :destroy


  resources :suppliers, only: [:index, :new, :create] do
    resources :services, only: [:index]
    resources :availabilities, only: [:new, :create]
    resources :images, only: [:new, :create]
  end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :service
  belongs_to :area
  has_many :bundle_lines
  has_many :reviews
  has_many :availabilities
  has_many :images, dependent: :destroy
  has_many :users, through: :reviews
  validates :description, presence: true
  validates :address, :capacity, presence: true, if: :is_a_place?
  monetize :price_cents
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # include PgSearch

  # pg_search_scope :search_by_price_category_address_capacity,
  #   against: [ :price, :category, :address, :capacity ],
  #   using: {
  #     tsearch: { prefix: true } # <-- now `superman batm` will return something!
  #   }
  private

  def is_a_place?
    return self.service.category == "lieu"
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
    @services = Service.all
    @areas = Area.all
    @supplier = Supplier.new
    @availability = Availability.new
    @image = Image.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to suppliers_path
    else
      render :new
    end
  end

  def index
    @suppliers = Supplier.all
  end

  private

  def supplier_params
    params.require(:supplier).permit(:owner, :description, :price, :avg_rating, :originality, :email, :capacity, :address, :service_name, :service_id, :photo)
  end
end

app/views/suppliers/index.html.erb
<div class="container">
  <h1>You have created <%= @suppliers.count %> suppliers</h1>


  <%= link_to new_supplier_path do %>
    <i class="fa fa-plus-square" aria-hidden="true"></i>
    <span>Add a new supplier</span>
  <% end %>
</div>

app/views/suppliers/new.html.erb
<div class="container">
  <h1>Add a new supplier</h1>


  <%= simple_form_for([@supplier]) do |f| %>
    <%= f.input :owner %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :avg_rating %>
    <%= f.input :originality %>
    <%= f.input :email %>
    <%= f.input :capacity %>
    <%= f.input :address %>
    <%= f.input :service_name %>
    <%= f.association :service, collection: Service.order(:category), label_method: :category, prompt: "Choose a service" %>
    <%= f.association :areas, collection: Area.order(:region), as: :check_boxes, label_method: :working_area, prompt: "Choose an area" %>
    <%= f.simple_fields_for :images do |p| %>
      <%= p.input :photo, as: :file %>
      <%= p.input :photo_cache, as: :hidden %>
    <% end %>
    <%= f.simple_fields_for :availabilities do |p| %>
      <%= p.input :starts_on %>
      <%= p.input :ends_on %>
    <% end %>




    <br>
    <%= f.submit class:'btn-validate' %>
  <% end %>
</div>